# Generated by Django 3.2.6 on 2021-11-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerInfo',
        ),
        migrations.DeleteModel(
            name='PolicyInfo',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['location', 'description']},
        ),
    ]
