# Generated by Django 3.2.6 on 2021-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210808_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
