# Generated by Django 3.2.6 on 2021-11-01 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.BooleanField()),
                ('purchase_location', models.CharField(blank=True, max_length=200)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('year', models.IntegerField()),
                ('tags', models.ManyToManyField(blank=True, related_name='movie', to='media.Tag')),
            ],
            options={
                'ordering': ['year', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.BooleanField()),
                ('purchase_location', models.CharField(blank=True, max_length=200)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('author', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='book', to='media.Tag')),
            ],
            options={
                'ordering': ['author', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.BooleanField()),
                ('purchase_location', models.CharField(blank=True, max_length=200)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('artist', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='album', to='media.Tag')),
            ],
            options={
                'ordering': ['artist', 'description'],
            },
        ),
    ]
