# Generated by Django 3.2.6 on 2021-11-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='photo',
        ),
    ]
