name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  django:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: "pipenv"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: Run Tests
      run: |
        pipenv run python manage.py test
